apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}-autoscaler-config
  labels:
  {{- include "cluster-autoscaler.labels" . | nindent 4 }}
data:
  config.yaml: |
    url: {{ .Values.whiteCruiserConfig.url }}
    token: {{ .Values.whiteCruiserConfig.token }}
    clusterName: {{ .Values.whiteCruiserConfig.clusterName }}
    clusterNamespace: {{ .Values.whiteCruiserConfig.clusterNamespace }}