apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}-rancher-ca
  labels:
  {{- include "cluster-autoscaler.labels" . | nindent 4 }}
data:
  ca-certificates.crt: {{ .Values.rancherCa.caCertificatesCrt | toYaml | indent 1
    }}